[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#e5c07b"

[colors.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#e5c07b"

[colors.primary]
background = "#1e2127"
foreground = "#abb2bf"

[window.dimensions]
columns = 80
lines = 24

[font]
size = 14.0
  normal = { family = "Hack Nerd Font", style = "Regular" }
  bold = { family = "Hack Nerd Font", style = "Bold" }
